services:
  guard: &guard
    tty: true
    stdin_open: true
    environment:
      RACK_ENV: test
    build:
      context: .
      args:
        CONTAINER_GID: '${CONTAINER_GID:-1000}'
        CONTAINER_UID: '${CONTAINER_UID:-1000}'
    restart: unless-stopped
    user: $CONTAINER_UID:$CONTAINER_GID
    env_file: .env
    command: "bundle exec guard"
    volumes:
      - ./:/opt/

  app:
    <<: *guard
    environment:
      RACK_ENV: development
    healthcheck:
      test: ["CMD", "curl", "-f", "-o", "/dev/null", "http://127.0.0.1:3000/api/ping"]
      interval: 10s
      timeout: 5s
      retries: 6
      start_period: 5s
    # command: "bundle exec puma"
    ports:
      - 3000:3000
